// Code generated by "stringer -type token -linecomment"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_EOF-1]
	_ = x[_Name-2]
	_ = x[_Literal-3]
	_ = x[_Semi-4]
	_ = x[_Comma-5]
	_ = x[_Lbrace-6]
	_ = x[_Rbrace-7]
	_ = x[_Lbrack-8]
	_ = x[_Rbrack-9]
}

const _token_name = "eofnameliteralnewlinecomma{}[]"

var _token_index = [...]uint8{0, 3, 7, 14, 21, 26, 27, 28, 29, 30}

func (i token) String() string {
	i -= 1
	if i >= token(len(_token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
